# Generated by Django 5.2.3 on 2025-08-21 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lugar', models.TextField(blank=True, null=True)),
                ('nom_lugar2', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion2', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('anios_experiencia', models.PositiveIntegerField(blank=True, null=True)),
                ('adultos_ninos', models.CharField(blank=True, choices=[('Solo adultos', 'Solo adultos'), ('Solo niños', 'Solo niños'), ('Ambos', 'Adultos y niños')], max_length=20, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='perfiles_usuario')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion2', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto1', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto2', models.CharField(blank=True, max_length=100, null=True)),
                ('especialidades', models.ManyToManyField(blank=True, to='autenticacion.especialidad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.tipousuario')),
            ],
        ),
    ]
