# Generated by Django 5.1.6 on 2025-02-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_tipousuario_alter_perfilusuario_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='proximo_rdv',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='especialidades',
            field=models.ManyToManyField(blank=True, to='autenticacion.especialidad'),
        ),
    ]
