# Generated by Django 5.1.6 on 2025-02-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_especialidad_perfilusuario_proximo_rdv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
