# Generated by Django 5.1.6 on 2025-05-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0005_perfilusuario_anios_experiencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='proximo_rdv',
        ),
    ]
