# Generated by Django 5.1.6 on 2025-05-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0006_remove_perfilusuario_proximo_rdv'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='adultos_ninos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='direccion2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nom_lugar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nom_lugar2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ubicacion2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
