# Generated by Django 5.1.6 on 2025-06-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0007_perfilusuario_adultos_ninos_perfilusuario_direccion2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='adultos_ninos',
            field=models.CharField(blank=True, choices=[('Solo adultos', 'Solo adultos'), ('Solo niños', 'Solo niños'), ('Ambos', 'Adultos y niños')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
