# Generated by Django 5.2.3 on 2025-09-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0003_donacionsection_canceled_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donacion',
            options={'verbose_name': 'Lista de Donaciones', 'verbose_name_plural': 'Lista de Donaciones'},
        ),
        migrations.RemoveField(
            model_name='donacionsection',
            name='progreso',
        ),
        migrations.AlterField(
            model_name='donacionsection',
            name='slug',
            field=models.SlugField(default='Pagina Principal Donaciones', help_text='Ej: home_callout', max_length=60, unique=True),
        ),
    ]
