# Generated by Django 5.2.3 on 2025-10-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0004_alter_donacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donacion',
            options={},
        ),
        migrations.AddField(
            model_name='donacionsection',
            name='progreso',
            field=models.PositiveIntegerField(default=100, help_text='0–100 (muestra la barra de progreso)'),
        ),
        migrations.AlterField(
            model_name='donacionsection',
            name='slug',
            field=models.SlugField(help_text='Ej: home_callout', max_length=60, unique=True),
        ),
    ]
