# Generated by Django 5.2.5 on 2025-10-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0004_alter_donacionsection_progreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacionsection',
            name='progreso',
        ),
    ]
