# Generated by Django 5.2.3 on 2025-10-08 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0003_donacionsection_canceled_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacionsection',
            name='progreso',
        ),
    ]
