# Generated by Django 5.2.5 on 2025-10-13 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0023_merge_20251010_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageHeader',
        ),
        migrations.AlterField(
            model_name='guidedvisit',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, db_default=datetime.datetime(2025, 10, 13, 15, 46, 17, 545182, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='guidedvisit',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, db_default=datetime.datetime(2025, 10, 13, 15, 46, 17, 545158, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='guidedvisitphoto',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, db_default=datetime.datetime(2025, 10, 13, 15, 46, 17, 545830, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='guidedvisitphoto',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, db_default=datetime.datetime(2025, 10, 13, 15, 46, 17, 545804, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='visitslanding',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, db_default=datetime.datetime(2025, 10, 13, 15, 46, 17, 544548, tzinfo=datetime.timezone.utc)),
        ),
    ]
