# Generated by Django 5.2.5 on 2025-12-27 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0027_alter_guidedvisit_actualizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidedvisit',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, db_default=datetime.datetime(2025, 12, 27, 18, 20, 7, 86312, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='guidedvisit',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, db_default=datetime.datetime(2025, 12, 27, 18, 20, 7, 86299, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='guidedvisitphoto',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, db_default=datetime.datetime(2025, 12, 27, 18, 20, 7, 86917, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='guidedvisitphoto',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, db_default=datetime.datetime(2025, 12, 27, 18, 20, 7, 86903, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='visitslanding',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, db_default=datetime.datetime(2025, 12, 27, 18, 20, 7, 85711, tzinfo=datetime.timezone.utc)),
        ),
    ]
