# Generated by Django 5.2.5 on 2025-12-29 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0029_alter_guidedvisit_actualizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidedvisit',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, db_default=datetime.datetime(2025, 12, 29, 1, 36, 23, 49109, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='guidedvisit',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, db_default=datetime.datetime(2025, 12, 29, 1, 36, 23, 49084, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='guidedvisitphoto',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, db_default=datetime.datetime(2025, 12, 29, 1, 36, 23, 49913, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='guidedvisitphoto',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, db_default=datetime.datetime(2025, 12, 29, 1, 36, 23, 49893, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='visitslanding',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, db_default=datetime.datetime(2025, 12, 29, 1, 36, 23, 48285, tzinfo=datetime.timezone.utc)),
        ),
    ]
