# Generated by Django 5.2.5 on 2025-12-29 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0030_alter_guidedvisit_actualizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidedvisit',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, db_default=datetime.datetime(2025, 12, 29, 1, 40, 28, 336584, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='guidedvisit',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, db_default=datetime.datetime(2025, 12, 29, 1, 40, 28, 336563, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='guidedvisitphoto',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, db_default=datetime.datetime(2025, 12, 29, 1, 40, 28, 337388, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='guidedvisitphoto',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, db_default=datetime.datetime(2025, 12, 29, 1, 40, 28, 337368, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='visitslanding',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, db_default=datetime.datetime(2025, 12, 29, 1, 40, 28, 335754, tzinfo=datetime.timezone.utc)),
        ),
    ]
