# Generated by Django 5.2.3 on 2025-09-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0020_rename_portadas_gallery_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='inicio/galerias/portadas/'),
        ),
    ]
