# Generated by Django 5.2.5 on 2025-09-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participa', '0006_rename_portadas_estancia_portada'),
    ]

    operations = [
        # Evitamos tocar la BD (ya está renombrado en muchos entornos),
        # pero mantenemos el historial de Django consistente.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameField(
                    model_name='estancia',
                    old_name='portadas',
                    new_name='portada',
                ),
            ],
        ),
    ]
